apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: enterprise-system-20260525-200210-x4a9holyqpni-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: enterprise-system-20260525-200210-x4a9holyqpni.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: enterprise-system-20260525-200210-x4a9holyqpni-service
            port:
              number: 80
